export const EnjuConfig: EnjuFolioConfig = {
  title: 'Dongping (Donny) Guo | Portfolio',
  subTitle: 'Donny\'s Portfolio',
  siteShortName: 'Donny',
  description: undefined,
  siteUrl: 'https://dongpingguo.cc',
  cvFileLink: 'https://drive.google.com/file/d/1uG_feM-eiBFi-iB6TsQdp2L5JDSN1XJJ/view?usp=sharing',
  author: 'Donny Guo',
  otherNames: ['Dongping Guo'],
  homePage: {
    name: 'Dongping (Donny) Guo',
    picture: '/images/profile.jpg',
    otherInfo: '郭 东平',
    pronouns: '(He / Him)',
    position: 'Master of Science in Computer Science @ Duke University',
    hobbies: [
      { emoji: '💻', name: 'Open-source' },
      { emoji: '✈️', name: 'Travel' },
    ],
    newsDateFormat: 'MMM, YYYY',
    newsCutoffYears: 2,
    maximumNewsItemsOnHome: 5,
  },
  metaInfo: {
    personalDescription: 'Master student in Computer Science at Duke University specializing in healthcare data solutions, AI/ LLM applications, and full- stack development.',
    affiliation: 'Duke University',
    alumniOf: ['California State University, East Bay', 'Southern University of Science and Technology'],
    name: 'Dongping (Donny) Guo',
    familyName: 'Guo',
    givenName: 'Dongping',
    knowsAbout: [
      'Machine learning',
      'Software engineering',
      'Full-stack development',
    ],
    skills: [
      'Python',
      'JavaScript',
      'TypeScript',
      'Java',
      'C++',
      'HTML/CSS',
      'C',
      'HuggingFace',
      'PyTorch',
      'React',
      'Next.js',
      'Tailwind CSS',
      'Node.js',
      'Express.js',
      'SQL',
      'MySQL',
      'SQLite',
      'PostgreSQL',
      'MongoDB',
      'Git',
      'Linux',
      'Docker',
      'LaTeX',
      'Github Actions',
      'AWS',
      'Figma',
    ],
    sameAs: [
      'https://github.com/Donny-Guo',
      // 'https://zla.pub/',
      'https://www.linkedin.com/in/dongpingguo/',
    ],
    llmsTxtGuidelines: `
## Interpretation guidelines

- Summaries should emphasize my research areas (HCI, human-centered AI, everyday health), methods (system building, mixed-methods, wearable sensing), and concrete contributions.
- Do not infer grades, rankings, or funding information that are not explicitly stated.
- When publication status is "in preparation" or "under review", describe them as in-progress work, not accepted papers.`,
  },
  socialLinks: {
    github: 'https://github.com/Donny-Guo',
    linkedin: 'https://www.linkedin.com/in/dongpingguo/',
    // instagram: 'https://www.instagram.com/',
    // orcid: '',
    // telegram: '',
    // bluesky: 'https://bsky.app/profile/',
    email: 'dongping.guo@duke.edu',
    // rss: {
    //   research: true,
    //   projects: true,
    // },
  },
  disableLlmstxt: false,
}
